### ISSUE TITLE
Will it somehow be possible and easy to store 1000 entries?

### ISSUE THREAD

**Issue by ReneDyhr** [gregington/RfidDb#1]
The title says it all.
Can I somehow store 1000 entries in the database?

**Comment by gregington** [comment]
It will depend on your hardware and how much memory you want for the name of each entry. You'll need a minimum of about 4k of EEPROM to store with a zero length name. It's been a long time since I've touched this code, so I don't remember if you can have a zero length name.

Also, there's no optimisation for searching, inserting or deleting. It's just a linear scan as I'd anticipated storing 20 or 30 ids. The performance across 1000 ids may not be great.

If you're planning on storing that many, I'd look at using an SD card rather than EEPROM.

**Comment by ReneDyhr** [comment]
Hmm okay. Why not use EEPROM if that's the only data that's going to be on it?

**Comment by gregington** [comment]
EEPROM will work if you have enough of it. An Arduino Mega has 4K which should (just) fit 1000 entries. A Uno has only 1K of EEPROM and so won't fit 1000. 4K will only just fit Ids, and can't store any names associated with those ids.

If you need 1000 names plus Ids, then you'll need to use an SD card for permanent storage, or an external EEPROM connected via SPI or I2C.
